### ISSUE TITLE
Incompatible/error with Kodi 19.0-alpha1?

### ISSUE THREAD

**Issue by cscd98** [xbmc-adult/xbmc-adult#319]
Ubuntu 19.10 (eoan).
Kodi 19.0-alpha1

Kodi.logs
```
2020-01-07 14:40:05.526 T:895  NOTICE: Starting Kodi (19.0-ALPHA1 Git:20200107-e9806a39ab). Platform: Linux x86 64-bit
2020-01-07 14:40:05.526 T:895  NOTICE: Using Release Kodi x64 build
2020-01-07 14:40:05.526 T:895  NOTICE: Kodi compiled 2020-01-07 by GCC 8.3.0 for Linux x86 64-bit version 5.0.21 (327701)
2020-01-07 14:40:05.526 T:895  NOTICE: Running on Ubuntu 19.10, kernel: Linux x86 64-bit version 5.3.0-26-generic
```

```
2020-01-07 14:46:03.943 T:895   ERROR: Control 55 in window 10025 has been asked to focus, but it can't
2020-01-07 14:46:04.086 T:1227   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'SyntaxError'>
                                            Error Contents: invalid syntax (videodevil.py, line 1402)
                                            Traceback (most recent call last):
                                              File "/home/kodi/.kodi/addons/plugin.video.videodevil/default.py", line 21, in <module>
                                                Main()
                                              File "/home/kodi/.kodi/addons/plugin.video.videodevil/default.py", line 15, in __init__
                                                self.run()
                                              File "/home/kodi/.kodi/addons/plugin.video.videodevil/default.py", line 18, in run
                                                import videodevil
                                              File "/home/kodi/.kodi/addons/plugin.video.videodevil/videodevil.py", line 1402
                                                except Exception, e:
                                                                ^
                                            SyntaxError: invalid syntax
                                            -->End of Python script error report<--
2020-01-07 14:46:04.101 T:1226   ERROR: GetDirectory - Error getting plugin://plugin.video.videodevil/
2020-01-07 14:46:04.114 T:895   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.videodevil/) failed
```

**Comment by Gujal00** [comment]
Yes Videodevil wont work in Kodi 19 as it is Python2 addon and Kodi 19 only supports Python 3 addons

**Comment by mrdougquaid** [comment]
This commit will fix the issue you encountered. There may be others. Please let us know, I do not run kodi19 yet. 
Thanks for the bug report

**Comment by Gujal00** [comment]
@mrdougquaid 
The whole python code needs to be redone for all byte string, unicode string, new urllib, etc.
Also all the language files need to be redone from xml to po format
#320 raised to make Videdevil compatible with Kodi19 as well as existing Python2 based Kodi
