### ISSUE TITLE
VideoDevil 1.7.240 failed (kodi.log)

### ISSUE THREAD

**Issue by drrak** [xbmc-adult/xbmc-adult#332]
_RPi4, Kodi 18.5, LibreELEC 9.2.0, VideoDevil 1.7.240_
```
2020-03-16 16:59:46.350 T:2844783472  NOTICE: Register - new cec device registered on cec->RPI: CEC Adapter (2708:1001)
2020-03-16 16:59:52.458 T:2606838640   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: No module named lib2to3.pgen2.parse
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.videodevil/default.py", line 21, in <module>
                                                Main()
                                              File "/storage/.kodi/addons/plugin.video.videodevil/default.py", line 15, in __init__
                                                self.run()
                                              File "/storage/.kodi/addons/plugin.video.videodevil/default.py", line 18, in run
                                                import videodevil
                                              File "/storage/.kodi/addons/plugin.video.videodevil/videodevil.py", line 7, in <module>
                                                from past.builtins import basestring
                                              File "/storage/.kodi/addons/script.module.future/libs/past/__init__.py", line 88, in <module>
                                                from past.translation import install_hooks as autotranslate
                                              File "/storage/.kodi/addons/script.module.future/libs/past/translation/__init__.py", line 41, in <module>
                                                from lib2to3.pgen2.parse import ParseError
                                            ImportError: No module named lib2to3.pgen2.parse
                                            -->End of Python script error report<--
2020-03-16 16:59:52.511 T:2615231344   ERROR: GetDirectory - Error getting plugin://plugin.video.videodevil/
2020-03-16 16:59:52.515 T:3011514384   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.videodevil/) failed
```

**Comment by Gujal00** [comment]
Identical to #324 
Solution is in the comments of that issue

**Comment by drrak** [comment]
_Translator:_
Everything works in the latest version of Kodi/Libreelec. 

Thanks.
