### ISSUE TITLE
Fantasticc is broken

### ISSUE THREAD

**Issue by duboisst** [xbmc-adult/xbmc-adult#88]
Fantasticc is broken since last commit f38010dd629546e0eb388b92dd466a76d4372a30

Stack Trace:
```
21:17:57 T:2148   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnboundLocalError'>
                                            Error Contents: local variable 'param' referenced before assignment
                                            Traceback (most recent call last):
                                              File "C:\Users\stephane\AppData\Roaming\Kodi\addons\plugin.video.fantasticc\default.py", line 576, in <module>
                                                topparams = get_params()
                                              File "C:\Users\stephane\AppData\Roaming\Kodi\addons\plugin.video.fantasticc\default.py", line 541, in get_params
                                                return param
                                            UnboundLocalError: local variable 'param' referenced before assignment
                                            -->End of Python script error report<--
```

**Comment by mrdougquaid** [comment]
Thanks for fixing this
